import React, { useState, useEffect } from 'react';
import { reportsAPI } from '../api-client';
import { useCRUD } from '../hooks/useAPI';
import { Table, Button, Modal, Input, Select, Card, Textarea } from '../components';

export const ReportsView = () => {
  const { items: reports, loading, error, fetchAll, create, update, remove } = useCRUD(reportsAPI);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingReport, setEditingReport] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    type: 'financial',
    description: '',
    parameters: '',
    generated_by: '',
    file_path: '',
  });

  useEffect(() => {
    fetchAll();
  }, []);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      if (editingReport) {
        await update(editingReport.id, formData);
      } else {
        await create(formData);
      }

      setIsModalOpen(false);
      resetForm();
      fetchAll();
    } catch (err) {
      console.error('Error saving report:', err);
    }
  };

  const handleEdit = (report) => {
    setEditingReport(report);
    setFormData({
      name: report.name || '',
      type: report.type || 'financial',
      description: report.description || '',
      parameters: report.parameters || '',
      generated_by: report.generated_by || '',
      file_path: report.file_path || '',
    });
    setIsModalOpen(true);
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this report?')) {
      try {
        await remove(id);
        fetchAll();
      } catch (err) {
        console.error('Error deleting report:', err);
      }
    }
  };

  const resetForm = () => {
    setFormData({
      name: '',
      type: 'financial',
      description: '',
      parameters: '',
      generated_by: '',
      file_path: '',
    });
    setEditingReport(null);
  };

  const getTypeBadge = (type) => {
    const colors = {
      financial: 'bg-green-100 text-green-800',
      operational: 'bg-blue-100 text-blue-800',
      customer: 'bg-purple-100 text-purple-800',
      inventory: 'bg-orange-100 text-orange-800',
      performance: 'bg-indigo-100 text-indigo-800',
    };
    return (
      <span className={`px-2 py-1 rounded-full text-xs font-medium ${colors[type] || colors.operational}`}>
        {type.toUpperCase()}
      </span>
    );
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString();
  };

  const columns = [
    { header: 'Report Name', accessor: 'name' },
    {
      header: 'Type',
      render: (row) => getTypeBadge(row.type),
    },
    { header: 'Generated By', accessor: 'generated_by' },
    {
      header: 'Created',
      render: (row) => formatDate(row.created_at),
    },
    {
      header: 'Actions',
      render: (row) => (
        <div className="flex gap-2">
          <Button size="sm" variant="secondary" onClick={() => handleEdit(row)}>
            Edit
          </Button>
          <Button size="sm" variant="danger" onClick={() => handleDelete(row.id)}>
            Delete
          </Button>
        </div>
      ),
    },
  ];

  const reportTypeOptions = [
    { value: 'financial', label: 'Financial' },
    { value: 'operational', label: 'Operational' },
    { value: 'customer', label: 'Customer' },
    { value: 'inventory', label: 'Inventory' },
    { value: 'performance', label: 'Performance' },
  ];

  return (
    <div className="p-4 space-y-4 bg-gray-50 min-h-screen">
      <div className="flex items-center justify-between bg-white border border-gray-200 rounded-lg px-4 py-2 shadow-sm">
        <div className="flex items-center justify-between w-full">
          <div>
            <h1 className="text-base font-bold text-gray-800">Reports Management</h1>
            <p className="text-xs text-gray-400 ml-2">Building Care Solutions - {reports.length} Reports</p>
          </div>
          <button
            onClick={() => setIsModalOpen(true)}
            className="px-3 py-1.5 bg-green-600 text-white text-xs font-semibold rounded-lg hover:bg-green-700 transition-colors"
          >
            Generate Report
          </button>
        </div>
      </div>

      <Card title="" subtitle="" actions={null}>
        {error && (
          <div className="mb-4 p-4 bg-red-100 text-red-700 rounded">
            Error: {error}
          </div>
        )}

        <Table
          columns={columns}
          data={reports}
          loading={loading}
          emptyMessage="No reports found. Generate your first report to get started."
        />
      </Card>

      <Modal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false);
          resetForm();
        }}
        title={editingReport ? 'Edit Report' : 'Generate New Report'}
      >
        <form onSubmit={handleSubmit}>
          <Input
            label="Report Name"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            required
            placeholder="e.g., Monthly Revenue Report"
          />

          <Select
            label="Report Type"
            name="type"
            value={formData.type}
            onChange={handleInputChange}
            required
            options={reportTypeOptions}
          />

          <Textarea
            label="Description"
            name="description"
            value={formData.description}
            onChange={handleInputChange}
            placeholder="Brief description of the report"
            rows={3}
          />

          <Textarea
            label="Parameters (JSON)"
            name="parameters"
            value={formData.parameters}
            onChange={handleInputChange}
            placeholder='{"start_date": "2024-01-01", "end_date": "2024-12-31"}'
            rows={3}
          />

          <Input
            label="Generated By"
            name="generated_by"
            value={formData.generated_by}
            onChange={handleInputChange}
            placeholder="Your name or system"
          />

          <Input
            label="File Path"
            name="file_path"
            value={formData.file_path}
            onChange={handleInputChange}
            placeholder="/reports/monthly_revenue_2024.pdf"
          />

          <div className="flex justify-end gap-2 mt-6">
            <Button
              type="button"
              variant="secondary"
              onClick={() => {
                setIsModalOpen(false);
                resetForm();
              }}
            >
              Cancel
            </Button>
            <Button type="submit">
              {editingReport ? 'Update' : 'Generate'} Report
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
};

export default ReportsView;
